// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SystemMonitoring.Backend.Data;

namespace SystemMonitoring.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210223021151_ReoccurringJobCreation")]
    partial class ReoccurringJobCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SystemMonitoring.Backend.Models.CurrentJobResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("Awaiting")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Deleted")
                        .HasColumnType("integer");

                    b.Property<int>("Enqueued")
                        .HasColumnType("integer");

                    b.Property<int>("Failed")
                        .HasColumnType("integer");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<int>("Processing")
                        .HasColumnType("integer");

                    b.Property<int>("Scheduled")
                        .HasColumnType("integer");

                    b.Property<int>("Succeeded")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CurrentJobResults");
                });

            modelBuilder.Entity("SystemMonitoring.Backend.Models.ReoccurringJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Conditional")
                        .HasColumnType("text");

                    b.Property<string>("CronString")
                        .HasColumnType("text");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PriorityField")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReoccurringJob");
                });

            modelBuilder.Entity("SystemMonitoring.Backend.Models.TestForHangfire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Job")
                        .HasColumnType("text");

                    b.Property<string>("RunTime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestForHangfire");
                });

            modelBuilder.Entity("SystemMonitoring.Backend.Models.TotalJobResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFailedJobs")
                        .HasColumnType("integer");

                    b.Property<int>("TotalJobs")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSuccessfulJobs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TotalJobResults");
                });
#pragma warning restore 612, 618
        }
    }
}
